### ISSUE TITLE
Appveyor: Consider adding '-y' to the 7-zip command-line

### ISSUE THREAD

**Issue by anjohnson** [epics-base/ci-scripts#39]
In the event that 7-zip tries to unpack something that is already there, it would be good for the job to not sit idly waiting for user-input that will never come, e.g.:
```
INFO] Installing Strawberry Perl 5.30.0.1
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 155000167 bytes (148 MiB)
Extracting archive: perl-5.30.0.1.zip
--
Path = perl-5.30.0.1.zip
Type = zip
Physical Size = 155000167
Would you like to replace the existing file:
  Path:     C:\strawberry\DISTRIBUTIONS.txt
  Size:     13324 bytes (14 KiB)
  Modified: 2020-03-17 05:35:54
with the file from archive:
  Path:     DISTRIBUTIONS.txt
  Size:     12726 bytes (13 KiB)
  Modified: 2019-05-23 14:23:24
? (Y)es / (N)o / (A)lways / (S)kip all / A(u)to rename all / (Q)uit?
```
Giving 7-zip a `-y` flag would prevent that and allow the job to continue.

**Comment by ralphlange** [comment]
Actually, this would overwrite the existing Strawberry Perl installation on the Visual Studio 2019 image with a different version that has been downloaded. I don't know if this is desirable.

Downloading and unpacking Perl has been removed from ci-scripts with 519b75aef23d24cb7ea16bae3fed829d9a48be72 two weeks ago.
Even before, the ci-scripts module never placed Strawberry Perl in that location.
Your issue seems to appear with one of the pre-existing AppVeyor CI scripts. One of the reasons for developing ci-scripts was to avoid such subtle differences in how things are done.

Not really an issue in the scope of ci-scripts, is it? I would not want to unpack something downloaded into an existing structure, unless the downloaded archive is exactly intended to be used like that.
